### ISSUE TITLE
Contributor License Agreement URL not working

### ISSUE THREAD

**Issue by johnboyes** [getgauge/gauge-bot#16]
Gauge's [CONTRIBUTING.md](https://github.com/getgauge/gauge/blob/master/CONTRIBUTING.md) states that in order to submit code contributions, one first needs to to read and sign the Contributor License Agreement.

The [Contributor License Agreement page](https://gauge-bot.herokuapp.com/cla/) is broken though, it says:

`Cannot GET /cla/`

**Comment by sriv** [comment]
That is old news! Thanks for raising this. We've moved away from CLA (and hence the broken link).

Presently, we follow the Developer Certificate of Origin (DCO) - https://developercertificate.org/

Gauge needs users to sign their commits, and there is no need to sign a CLA anymore.

I'll update the Contributing Guidelines with this. This was an oversight, apologies.
